pull_request_rules:
  - name: vm7 bot account identity binding control
    conditions:
      - base = vm7-botacct-critical-target
      - title ~= ^VM7_BOTACCT_
    actions:
      merge:
        method: merge
        merge_bot_account: "{{ author }}"
